export const LOGIN = "LOGIN"
export const ONSTART = "ONSTART"
export const LOGOUT = "LOGOUT"
export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_CART = "UPDATE_CART"
export const COUNT = "COUNT"